{% set name = "ibmpairs" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9988249be1ee9b7ff7e963af8654f3ffa9b1d9069ffefbb00950e830df07e134

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - fs
    - future
    - futures
    - jsonschema
    - numpy
    - pandas
    - pillow >=1.6
    - python
    - pytz
    - requests >=2.4
    - shapely

test:
  imports:
    - ibmpairs
about:
  home: https://ibmpairs.mybluemix.net
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: open source Python modules for the IBM PAIRS Geoscope platform
  doc_url: https://pairs.res.ibm.com/tutorial/
  dev_url: https://github.com/ibm/ibmpairs

extra:
  recipe-maintainers:
    - cmalbrec
