{% set name = "ibmpairs" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b022b0801055bcc354535f159f070ddadbb246fe250daadf5d0f2f28c39eed13

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - fs
    - future
    - numpy
    - pandas
    - pillow >=1.6
    - python
    - pytz
    - requests >=2.4
    - shapely

test:
  imports:
    - ibmpairs
about:
  home: "https://ibmpairs.mybluemix.net"
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "open source Python modules for the IBM PAIRS Geoscope platform"
  doc_url: "https://pairs.res.ibm.com/tutorial/"
  dev_url: "https://github.com/ibm/ibmpairs"

extra:
  recipe-maintainers:
    - cmalbrec
